### ISSUE TITLE
Webassembly in nodejs

### ISSUE THREAD

**Issue by stepancar** [lume/glas#140]
Hello! 

I'm curious, If I want to run that webassembly in nodejs context, how it would access graphics card? In browser context browser provides webgl to webasm, but is it possible to run that webasm outside of browser and still have webglRenderingContext?

Thank you!

**Comment by trusktr** [comment]
Hello! In a browser context the browser actually doesn't provide WebGL to Wasm, and glue code has to be created. Depending on your language, some tooling automatically outputs this JavaScript glue code. For example, emscripten will putput JavaScript along with your Wasm output, so that the JavaScript can provide the link between Wasm and WebGL APIs.

You can also write JavaScript bindings yourself, as the WebAssembly API lets you provide functions from JavaScript to be imported into a WebAssembly module (look for "webassembly imports"), and when WebAssembly calls these functions, these functions can do things like interact with JavaScript's WebGL APIs.

In Node, its the same thing, except that WebGL doesn't exist out of the box, but you can install Luis Blanco's (@raub) excellent `webgl-raub` package that adds WebGL APIs to Node.js.

If you're writing code in Rust, for example, then after you add webgl-raub in your node app, there should be little left for a Rust app to just work. If it complains about any DOM APIs missing once you run the code, you can implement what is missing. The `webgl-raub` package and related packages already try to polyfill some common things that WebGL apps need like `document.createElement('canvas')`, etc.

Hope that helps!

**Comment by stepancar** [comment]
@trusktr thank you for your answer! I know about webgl-raub package, tried it but no luck with canvaskit from skia. It's seems like it provides not full support of webgl. Currently we use headless-gl which is not ideal also and I was curious about wasm, expected that in wasm world tools like emascripten could provide true webgl implementation and bindings.
@trusktr If you have deep experience with webgl-raub, may I ask you to answer question here https://github.com/node-3d/webgl-raub/issues/24 ? thank you!
